-- Same model as init/01-contacts.sql (upstream Postgres DDL), expressed for SQLite.
-- SQLite has no BOOLEAN/DATE/TIMESTAMPTZ storage classes; the ports store booleans as 0/1,
-- dates as ISO-8601 text (YYYY-MM-DD) and timestamps as ISO-8601 UTC text.
CREATE TABLE IF NOT EXISTS contacts
(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  account_id TEXT,
  active_tracker_count INTEGER,
  assistant_name TEXT,
  assistant_phone TEXT,
  birthdate TEXT,
  can_allow_portal_self_reg INTEGER,
  contact_id TEXT,
  contact_name TEXT,
  created_by_id TEXT,
  created_date TEXT,
  currency_iso_code TEXT,
  department TEXT,
  do_not_call INTEGER,
  email TEXT,
  external_id TEXT,
  fax TEXT,
  first_name TEXT,
  has_opted_out_of_email INTEGER,
  has_opted_out_of_fax INTEGER,
  has_privacy_hold INTEGER,
  home_phone TEXT,
  individual_id TEXT,
  is_deleted INTEGER,
  is_email_bounced INTEGER,
  is_locked INTEGER,
  is_person_account INTEGER,
  is_priority_record INTEGER,
  last_activity_date TEXT,
  last_modified_by_id TEXT,
  last_modified_date TEXT,
  last_name TEXT,
  lead_source TEXT,
  mailing_city TEXT,
  mailing_country TEXT,
  mailing_postal_code TEXT,
  mailing_state TEXT,
  mailing_street TEXT,
  may_edit INTEGER,
  middle_name TEXT,
  mobile_phone TEXT,
  other_city TEXT,
  other_country TEXT,
  other_phone TEXT,
  other_postal_code TEXT,
  other_state TEXT,
  other_street TEXT,
  owner_id TEXT,
  phone TEXT,
  photo_url TEXT,
  record_type_id TEXT,
  salutation TEXT,
  suffix TEXT,
  system_mod_stamp TEXT,
  title TEXT
);
CREATE INDEX IF NOT EXISTS contacts_id_idx ON contacts (id);
CREATE INDEX IF NOT EXISTS contacts_mailing_city_idx ON contacts (mailing_city);
